### ISSUE TITLE
no-install flag not working

### ISSUE THREAD

**Issue by jdfreder** [jovyan/jupyter-devinstall#24]
I used `--no-install` and it still checked for installation dependencies and asked me how I wanted to install.

**Comment by jdfreder** [comment]
and it ended with a glorious 

```
Install Python packages
Error while executing PIP [TypeError: Cannot read property 'install' of undefined] TypeError: Cannot read property 'install' of undefined
    at PIP.run (/usr/local/lib/node_modules/jupyter-devinstall/lib/steps/pip.js:43:36)
    at /usr/local/lib/node_modules/jupyter-devinstall/lib/steps/base.js:129:34
    at process._tickCallback (node.js:356:9)
```
