### ISSUE TITLE
Windows errors with symbolic links.

### ISSUE THREAD

**Issue by SylvainCorlay** [jovyan/jupyter-devinstall#34]
First attempt to use Jupyter-devinstall in windows, I am getting the following error in initial the github repo check.:

```
Error while executing CheckGithub { [Error: write EPROTO]
  code: 'EPROTO',
  errno: 'EPROTO',
  syscall: 'write',
  address: undefined } Error: write EPROTO
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)
```

**Comment by SylvainCorlay** [comment]
When using `--no-bin-links`, the `jupyter-devinstall` is not found.
